### ISSUE TITLE
python3.6 字符串和字节串兼容问题/String and byte string compatibility issues

### ISSUE THREAD

**Issue by fun0gs** [guyingbo/shadowproxy#1]
以下是在测试HTTP代理（带密码）中发现的：
1. 字符串和字节串无法操作：line 773  
    version + b' 407 Proxy Authentication Required\r\n'
    改为：version.encode('utf-8') + b' 407 Proxy Authentication Required\r\n'
2. 字节串没有casefold()方法，代码中所有casefold()可以简单替换为lower()解决，str和bytes都可以调用

就简单说一下，git操作就懒得弄了...

**Comment by fun0gs** [comment]
挺好的一个工具:)

**Comment by fun0gs** [comment]
要是文档能更丰富一点就好了，比如-vv增加log级别，https代理的证书参数等，有些功能还是要靠猜和代码才用的来

**Comment by guyingbo** [comment]
1, 2两个问题都已fix
