### ISSUE TITLE
Example of rewriting request/response

### ISSUE THREAD

**Issue by mjallday** [guyingbo/shadowproxy#4]
Are there any examples of how to rewrite requests and responses as they pass through this proxy?

**Comment by guyingbo** [comment]
Usually Shadowproxy works as a server or client software, you don't deal with requests and responses directly.

**Comment by mjallday** [comment]
Understood. There’s a bunch out there like mitmproxy which do the same but support rewriting requests. I’ll look elsewhere. Thank you.
